### PR TITLE
Allow cmake unity build

### PR DESCRIPTION
**Pull request by waywardmonkeys**
I'm looking at doing Rust bindings for this and it would pull and build the sources. It would be nice to enable `CMAKE_UNITY_BUILD` in our build script to shorten up the build times.

On an old MacBook Pro (Intel, 2017 model), this is a decent improvement in build times.

In a regular build (with `ninja`):

```
❯ time ninja
[65/71] Linking CXX static library libchuffed.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libchuffed.a(template.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libchuffed.a(template.cpp.o) has no symbols
[71/71] Linking CXX executable fzn-chuffed
ninja  172.71s user 13.36s system 677% cpu 27.482 total
```

And with `cmake -DCMAKE_UNITY_BUILD=ON -GNinja ...`:

```
❯ time ninja
[12/16] Building CXX object CMakeFiles/chuffed.dir/Unity/unity_3_cxx.cxx.o
In file included from /Users/bruce/Development/configura/chuffed/ub/CMakeFiles/chuffed.dir/Unity/unity_3_cxx.cxx:22:
/Users/bruce/Development/configura/chuffed/chuffed/globals/minimum_weight_tree.cpp:30:9: warning: 'MIN' macro redefined [-Wmacro-redefined]
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
        ^
/Users/bruce/Development/configura/chuffed/chuffed/globals/tree.cpp:17:9: note: previous definition is here
#define MIN(a, b) ((a) < (b) ? (a) : (b))
        ^
1 warning generated.
[16/16] Linking CXX executable fzn-chuffed
ninja  84.39s user 3.23s system 661% cpu 13.236 total
```

So, we can see that it went from 27s to 13s in terms of total time.

I could add a CI config for this as well if there's interest.

(I'll submit a separate PR about `MIN`)

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -229,6 +229,15 @@ else()
   set(FLEX_FZNLexer_OUTPUTS ${PROJECT_SOURCE_DIR}/chuffed/flatzinc/generated_parser/lexer.yy.cpp)
 endif()
 
+# If CMAKE_UNITY_BUILD is enabled, we still want these files to be built separately
+# to avoid compilation errors.
+set_source_files_properties(
+    ${BISON_FZNParser_OUTPUTS}
+    ${FLEX_FZNLexer_OUTPUTS}
+  PROPERTIES
+    SKIP_UNITY_BUILD_INCLUSION ON
```
Comment (Dekker1) [inline CMakeLists.txt:238]: I haven't really looked at unity builds yet, but the improvement in build times are promising. Could you explain why these particular files would have to be skipped in the batched builds. Is this because it would otherwise not be guaranteed that the files have been generated?

File: chuffed/support/lengauer_tarjan.h [hunk 2]
```diff
@@ -1,3 +1,5 @@
+#pragma once
```
Comment (Dekker1) [inline chuffed/support/lengauer_tarjan.h]: Good spotting that this was missing. Could you change your commit to use `#ifdef` guards to match the rest of the codebase?

**Review by Dekker1 — CHANGES_REQUESTED** [review]

File: chuffed/support/lengauer_tarjan.h (hunk 2 above)
Comment (waywardmonkeys) [reply chuffed/support/lengauer_tarjan.h]: Done.

File: CMakeLists.txt (hunk 1 above)
Comment (waywardmonkeys) [reply CMakeLists.txt:238]: Conflicting definitions within them, so if they both get added to the same compile unit, it isn't happy.

**Review by Dekker1 — APPROVED** [review]
